# Generated by Django 5.0.4 on 2024-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='current_version',
            field=models.BooleanField(default=True, verbose_name='Признак текущей версии'),
        ),
    ]
