# Generated by Django 5.0.4 on 2024-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_version_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='number_version',
            field=models.IntegerField(verbose_name='Номер версии'),
        ),
    ]
