# Generated by Django 4.2.2 on 2024-06-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Может опубликовать товар'), ('can_edit_description', 'Может менять описание'), ('can_edit_category', 'Может менять категорию')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
